[project]
name = "CV"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ruhila S <ruhiresearcher209@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
r-tinytex = "0.53.*"
tectonic = "0.15.0.*"
python = "3.12.6.*"
