#+AUTHOR: Ruhila Goswami
#+email: ruhila@ieee.org
#+options: tags:nil title:nil toc:nil
# Usage: run scripts/org2tex.el on this file, then build the generated TeX.

* Configuration :ignoreheading:ignore:
:PROPERTIES:
:VISIBILITY: folded
:END:
#+begin_src emacs-lisp :exports none :eval always :results none
(org-babel-tangle)
#+end_src

** Theme :ignoreheading:ignore:
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: moderncv
#+LATEX_CLASS_OPTIONS: [11pt,a4paper,final,factor=1100,stretch=16,shrink=16]

* Preamble :ignoreheading:ignore:noexport:
The LaTeX setup is tangled to =preamble.tex= and included during export.

#+name: cv_preamble
#+begin_src latex :results none :tangle preamble.tex
\usepackage{xcolor}
\usepackage{fontspec}

% Stop bugging me about \es
\usepackage{xspace}
% moderncv themes
\moderncvstyle{classic}                             % style options are 'casual' (default), 'classic', 'banking', 'oldstyle' and 'fancy'
%\moderncvcolor{blue}                               % color options 'black', 'blue' (default), 'burgundy', 'green', 'grey', 'orange', 'purple' and 'red'

% Academic burgundy accent with neutral greys for a consistent application CV palette.
\definecolor{color0}{RGB}{35, 35, 35}
\definecolor{color1}{RGB}{100, 14, 39}
\definecolor{color2}{RGB}{82, 82, 82}

% scale the page layout (depreciated for more complicated stuff)
%\usepackage[scale=0.75]{geometry}

% change width of the column with the dates
\setlength{\hintscolumnwidth}{2.5cm}

%\PassOptionsToPackage[final, factor=1100, stretch=18, shrink=18 ]{microtype}
% The final option overrides global defaults. It greatly improves general appearance of the text. The stretch and shrink reduce bluriness[20,20 default]. The factor increases protrusion amount by 10%, [default 1000]
% Tracking allows for small caps, like in cites to be adjusted. The activate commands are to set protrusion.

\microtypecontext{spacing=nonfrench} 						% To preserve interword spacing via \nonfrenchspacing.

\SetExtraKerning[unit=space] 								% These produce more effects, from microtype with kerning.
    {encoding={*}, family={bch}, series={*}, size={footnotesize,small,normalsize}}
    {\textendash={400,400}, 								% en-dash, add more space around it
     "28={ ,150}, 											% Left bracket, add space from right
     "29={150, },											% Right bracket, add space from left
     \textquotedblleft={ ,150}, 							% Left quotation mark, space from right
     \textquotedblright={150, }} 							% Right quotation mark, space from left


\SetExtraKerning[unit=space]
  {encoding={*}, family={qhv}, series={b}, size={large,Large}}
  {1={-200,-200},
   \textendash={400,400}}

\SetTracking{encoding={*}, shape=sc}{40} 					% This is for better small caps with tracking and microtype.

\SetProtrusion{encoding={*},family={bch},series={*},size={6,7}}  % This enables better optical views.
              {1={ ,750},2={ ,500},3={ ,500},4={ ,500},5={ ,500},
               6={ ,500},7={ ,600},8={ ,500},9={ ,500},0={ ,500}}

% Page settings
\usepackage{geometry}
 \geometry{
 a4paper,
 % total={210mm,297mm},
 % left=15mm,
 % right=15mm,
 % top=10mm,
 % bottom=08mm,
 }

% required when changing page layout lengths
\AtBeginDocument{\recomputelengths}
\usepackage{xunicode}
\usepackage{xltxtra}
% \usepackage[utf8]{inputenc} (Xelatex expects UTF8 anyway)

% I like pretty logos
\usepackage{metalogo}

% Widen the letter spacing for logos
\setlogokern{La}{0.2pt}
\setlogokern{Xe}{0.2pt}
\setlogokern{eL}{0.2pt}
\setlogokern{Te}{0.2pt}
\setlogokern{aT}{0.2pt}
\setlogokern{eX}{0.2pt}

% Better Quotes (depreciated for this useage)
%\usepackage{epigraph}

% Poaching from Espresso's ug.tex

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%% New Commands and Environments %%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newcommand{\es}{\mbox{\textsf{ESPResSo}}\xspace}

% german word break/hyphenation rules that's with ngerman (we use english)
\usepackage[british,UKenglish,USenglish,american]{babel}

% insert dummy text (used in the letter)
%\usepackage{lipsum}

% used for \begin{comment}...\end{comment}
\usepackage{verbatim}

% use guilllemets in bibliography (not german.) Also autostyle superceeded babel
\usepackage[autostyle=true]{csquotes}

\usepackage[
	sorting=none,
	minbibnames=8,
	maxbibnames=9,
	block=space,
  defernumbers=true
]{biblatex}

\bibliography{publications}


% Vanity (https://tex.stackexchange.com/questions/359311/how-to-underline-name-of-specific-authors-in-biblatex)
\usepackage{xpatch}
\usepackage[normalem]{ulem} %for \uline

\newbox\savenamebox

% Actually I don't use the bold version anymore
\newbibmacro*{name:bbold}[2]{%
  \def\do##1{\iffieldequalstr{hash}{##1}{\setbox\savenamebox\hbox\bgroup \listbreak}{}}%
  % \def\do##1{\iffieldequalstr{hash}{##1}{\bfseries\setbox\savenamebox\hbox\bgroup \listbreak}{}}%
  \dolistloop{\boldnames}%
}

\newbibmacro*{name:ebold}[2]{%
  \def\do##1{\iffieldequalstr{hash}{##1}{\egroup\uline{\usebox\savenamebox}\listbreak}{}}%
  \dolistloop{\boldnames}%
}

\xpatchbibmacro{name:given-family}{\usebibmacro{name:delim}{#2#3#1}}{\usebibmacro{name:delim}{#2#3#1}\begingroup\usebibmacro{name:bbold}{#1}{#2}}{}{}

%\xpretobibmacro{name:given-family}{\begingroup\usebibmacro{name:bbold}{#1}{#2}}{}{}
\xapptobibmacro{name:delim}{\begingroup\normalfont}{}{}

\xapptobibmacro{name:given-family}{\usebibmacro{name:ebold}{#1}{#2}\endgroup}{}{}
\xapptobibmacro{name:delim}{\endgroup}{}{}

% Hash in the bbl file
\newcommand*{\boldnames}{}
\forcsvlist{\listadd\boldnames}{
  {f9515b75cdf9643ea5818174fe975e2b}, % Ruhi
  }

% get rid of the number-labels ([1], [2], etc.) in front of publications
\defbibenvironment{midbib}
{\list
	{}
	{
		\setlength{\leftmargin}{0mm}
		\setlength{\itemindent}{-\leftmargin}
		\setlength{\itemsep}{\bibitemsep}
		\setlength{\parsep}{\bibparsep}}
	}
	{\endlist}
{\item}


% add [DOI] and [PDF] fields at the end of each publication entry
\DeclareSourcemap{
	\maps[datatype=bibtex]{
		% the bibtex entry 'mydoi' gets mapped to 'usera'
		\map{
			\step[fieldsource=mydoi]
			\step[fieldset=usera, origfieldval]
		}
		% the bibtex entry 'mypdf' gets mapped to 'usera'
		\map{
			\step[fieldsource=mypdf]
			\step[fieldset=userb, origfieldval]
		}
	}
}

% [DOI] entries in publication
\DeclareFieldFormat{usera}{\color{color1}[\href{#1}{\textsc{doi}}]}
\AtEveryBibitem{
	% put [DOI] stuff at the end of a publication entry
	\csappto{blx@bbx@\thefield{entrytype}}{%
		\iffieldundef{usera}{
			% this gets invoked, once nothing is supplied
			% via the mypdf or mydoi value.
			% you could e.g. display a default thing here.
		}{\space\printfield{usera}}}
}

% [PDF] entries in publication
\DeclareFieldFormat{userb}{\color{color1}[\href{#1}{\textsc{pdf}}]}

\AtEveryBibitem{
	% put [DOI] stuff at the end of a publication entry
	\csappto{blx@bbx@\thefield{entrytype}}{\iffieldundef{userb}{}{\printfield{userb}}}
}

\renewcommand*{\mkbibnamegiven}[1]{%
	\ifitemannotation{highlight}
	{\textbf{#1}}
	{#1}}

	\renewcommand*{\mkbibnamefamily}[1]{%
	\ifitemannotation{highlight}
	{\textbf{#1}}
	{#1}
}


% Minion Pro is used as the main font, if you don't
% have it installed uncomment this line or choose another pretty font.
% Literata is also included.
%\setmainfont[Numbers=OldStyle]{Minion Pro}

\setmainfont[
Path = Fonts/MinionPro/,
Numbers=OldStyle,
Extension = .otf,
UprightFont = *_Regular,
ItalicFont = *_It,
BoldFont = *_Bold,
BoldItalicFont = *_BoldIt
]{MinionPro}

% Myriad Pro is used as the sans font, if you don't
% have it installed uncomment this line or choose another pretty font.
\setsansfont[
Path = Fonts/MyriadPro/,
Numbers=OldStyle,
Extension = .otf,
UprightFont = *_Regular,
ItalicFont = *_It,
BoldFont = *_Bold,
BoldItalicFont = *_BoldIt,
Ligatures=TeX,
Scale=MatchLowercase]{MyriadPro}

% the moderncv package will populate a lot of the pdf meta-information.
% this can be used to change some of these infos.
\AfterPreamble{\hypersetup{
  pdfcreator={XeLaTeX},
  pdftitle={Ruhila Goswami CV},
  colorlinks=true,
  urlcolor=color1,
  linkcolor=color1,
  citecolor=color1
}}

% for the icons (telephone, globe). I found the icons provided by the
% fontawesome package prettier than the standard moderncv icons.
\defaultfontfeatures{
    Path = Fonts/FontAwesome/ }

% personal data
\firstname{Ruhila}
\familyname{Goswami}
% \quote{}

% \faEnvelope \faPhone \faGithub \faGlobe

% I use the extrainfo command for additional information, since I
% want to use custom icons and have finer control over spacing.
\extrainfo{
	{\small\faEnvelope}\hspace{0.3em}ruhila@ieee.org\\
	{\small\faGithub}\hspace{0.3em}RuhiRG%\\
	% \faGlobe\hspace{0.3em}https://github.com/RuhiRG/
}


% \photo[84pt]{Picture/ruhi}

% spacing before (sub)sections
\newcommand{\spacesection}{\vspace{0.4cm}}
\newcommand{\spacesubsection}{\vspace{0.2cm}}

#+end_src

#+LATEX_HEADER: \input{preamble.tex}

* TeX Document Extras :ignoreheading:ignore:
#+begin_export latex

% Adapted from https://tex.stackexchange.com/a/170219/130845
\begin{tikzpicture}[remember picture,overlay]
      \node[anchor=north, yshift=-0.25cm] at (current page.north) {\underline{Last
		  updated on \today}};
\end{tikzpicture}

\maketitle

#+end_export

* Applicant Details
:PROPERTIES:
:CUSTOM_ID: applicant-details
:END:
#+begin_export latex
\cvitem{Current name}{Ruhila Goswami}
\cvitem{Previous name}{Ruhila S.}

\spacesection{}
#+end_export

* Research Profile
:PROPERTIES:
:CUSTOM_ID: research-profile
:END:
#+begin_export latex
\cvitem{\textsc{Focus}}{Evolutionary divergence in salmonids, linking dental and craniofacial phenotypes with population history, genome structure, and selection.}
\cvitem{\textsc{Interests}}{Population genetics; phenotypic-genotypic mapping; structural variation in genomes and selection; salmonid evolution; non-invasive methods.}
\cvitem{\textsc{Methods}}{Phylogenetic inference, genomic synteny, PCR-based sex determination, skeletal phenotyping, field sampling, and reproducible analysis in R and Python.}

\spacesection{}
#+end_export

* Education
:PROPERTIES:
:CUSTOM_ID: education
:END:
#+begin_export latex
\cventry{\textsc{2024--2026}}{M.S. Biological Science}{University of Iceland}{Reykjavík}{\emph{Iceland}}{(\textsc{Advisor: } Prof. Arnar Pálsson)}{\textsc{Thesis: }Evolutionary Divergence in Dental Variation and Sex Chromosome Architecture in Icelandic Brown Trout and Arctic Charr}

\cventry{\textsc{2021--2024}}{B.S. Biology (Major)}{Indian Institute of Science Education and Research (IISER)}{Mohali}{\emph{India}}{First Division with Honors}
\cventry{\textsc{2020}}{Intermediate (AISSCE)}{Velammal Vidyalaya, Ayanabakkam}{Chennai}{\emph{India}}{$83.8\%$ Central Board of Secondary Education (CBSE)}
\cventry{\textsc{2017}}{High School (AISSE)}{Velammal Vidyalaya, Ayanabakkam}{Chennai}{\emph{India}}{$10.0$ Cumulative Grade Point Average (CGPA) in Central Board of Secondary Education (CBSE)}

\spacesection{}
#+end_export

* Publications
:PROPERTIES:
:CUSTOM_ID: publications
:END:
#+begin_export latex
{\color{color1}\textsc{Manuscripts in Preparation}}

\cvitem{\textsc{In preparation}}{Evolutionary divergence in tooth numbers and bone shape by populations and species in Icelandic salmonids}

{\color{color1}\textsc{Conference Proceedings}}

\nocite{*}
\printbibliography[heading=none, env=midbib, keyword=conference]

{\color{color1}\textsc{Preprints}}

\nocite{*}
\printbibliography[heading=none, env=midbib, keyword=preprint]

\spacesection{}
#+end_export

* Presentations and Posters
:PROPERTIES:
:CUSTOM_ID: presentations-and-posters
:END:
#+begin_export latex
#+end_export

** Posters
:PROPERTIES:
:CUSTOM_ID: posters
:END:
#+begin_export latex
\cventry{\textsc{April 2026}}{Evolutionary divergence in tooth numbers and bone shape by populations and species in Icelandic salmonids}{Icelandic Ecological Society (Vistís)}{\underline{Ruhila Goswami}}{}{}
\cventry{\textsc{March 2026}}{Evolutionary divergence in tooth numbers and bone shape by populations and species in Icelandic salmonids}{NOWPAS}{\underline{Ruhila Goswami}}{}{}
\cventry{\textsc{October 2025}}{Evolutionary divergence in tooth numbers and bone shape by populations and species in Icelandic salmonids}{IceBio}{\underline{Ruhila Goswami}}{}{}
\cventry{\textsc{2025}}{Diversity in craniofacial elements by populations and sexes in salmonids of Iceland}{Icelandic Ecological Society (Vistís)}{\underline{Ruhila Goswami}}{Best Poster Award}{}
\cventry{\textsc{November 2022}}{Tracing Lineages of \textit{Salmo salar} through Histone sequence data}{BES Annual Meeting 2022}{\underline{Ruhila S. Goswami (née S.)}}{}{}

#+end_export

** Oral Presentations
:PROPERTIES:
:CUSTOM_ID: oral-presentations
:END:
#+begin_export latex
\cventry{\textsc{November 2022}}{High Throughput Reproducible Literate Phylogenetic Analysis}{IEEE PDGC 2022}{R. Goswami, \underline{Ruhila S. Goswami (née S.)}}{}{}
\cventry{\textsc{November 2022}}{Reproducible High Performance Computing Without Redundancy with Nix}{IEEE PDGC 2022}{R. Goswami, \underline{Ruhila S. Goswami (née S.)}, A. Goswami, S. Goswami and D. Goswami}{}{}
\cventry{\textsc{November 2022}}{Reproducible Literate Programming Workflows for Censored Data}{IOP Machine Learning for Healthcare}{R. Goswami, \underline{R. S.}}{}{}

\spacesection{}
#+end_export

* Honors and Awards
:PROPERTIES:
:CUSTOM_ID: honors-and-awards
:END:
#+begin_export latex
\cventry{\textsc{2025}}{Best Poster Award}{Icelandic Ecological Society (Vistís)}{}{}{}

\spacesection{}
#+end_export

* Research Experience
:PROPERTIES:
:CUSTOM_ID: research-experience
:END:
#+begin_export latex
\cventry{\textsc{Summer 2023}}{Prof. Arnar Pálsson}{University of Iceland}{}{Research Staff}{Studied the synteny of histone genes in salmonids, focusing on gene arrangement and neighboring genomic regions.}

\cventry{\textsc{Winter 2022}}{Prof. Debabrata Goswami}{IIT Kanpur}{}{Research Intern}{Studied the basics of non-linear optics and applications of optical tweezers in cancer cell research and microscopy.}

\cventry{\textsc{Winter 2022}}{Dr. Nagma Parveen}{IIT Kanpur}{}{Research Intern}{Studied wet-lab methods for viral mechanisms under external stimuli and began work on a SARS-CoV-2 pseudovirus protocol using an HIV-1 lentiviral packaging system with a luciferase reporter.}

\cventry{\textsc{Summer 2022}}{Prof. Arnar Pálsson}{University of Iceland}{}{Research Staff}{Detailed analysis in a literate and reproducible manner for simulating a series of possible molecular evolutionary pathways for the \textit{Salmonid} using phylogenetic trees. This involved the five steps on an HPC (High Performance Computer) with literate programming visualization in R:
  \begin{itemize}
          \item Data curation with NCBI databases
          \item Homology inference using similarity measures (BLAST)
          \item Multiple sequence alignment (MUSCLE5)
          \item Alignment trimming (Gblocks)
          \item Tree simulation with distance measures (BIONJ) and maximum likelihood approaches (RAxML-NG)
  \end{itemize}~\\
 \textsc{Project Report: }Computational Primitives for Evolutionary Paths ($\approx 147$ pages)
}

\cventry{\textsc{Summer 2021}}{Dr. Lolitika Mandal}{IISER Mohali}{}{Research Intern}{Explored genetic tools for working with \textit{Drosophila} from a wet-lab perspective of data collection and analysis.}

\spacesection{}
#+end_export

* Teaching Experience
:PROPERTIES:
:CUSTOM_ID: teaching-experience
:END:
#+begin_export latex
\cventry{\textsc{Spring 2026}}{LÍF401G Developmental Biology}{University of Iceland}{}{Teaching Assistant}{Course led by Prof. Adam Ray Smith. Assisted with embryo analysis for an 8 credit undergraduate developmental biology course.}

\cventry{\textsc{Fall 2025}}{LÍF541G Plant Physiology}{University of Iceland}{}{Teaching Assistant}{Course led by Prof. Victor Anthony Albert. Led student discussions in a 7.5 credit undergraduate course focused primarily on plant genetics.}

\cventry{\textsc{Spring 2025}}{LÍF403G Evolutionary Biology}{University of Iceland}{}{Teaching Assistant}{8 credit undergraduate course on evolutionary theory, natural selection, adaptation, and the history of life.}

\spacesection{}
#+end_export

* Research Skills
:PROPERTIES:
:CUSTOM_ID: research-skills
:END:
#+begin_export latex
\cvdoubleitem{\textsc{Genomics}}{Population genetics, genomic synteny, structural variation, PCR-based sex determination, non-invasive sampling}
           {\textsc{Phenotypes}}{Dental and craniofacial variation, bone extraction, otolith extraction, fish dissection, embryo analysis}

\cvdoubleitem{\textsc{Evolutionary methods}}{Phylogenetic tree construction (distance, maximum likelihood, Bayesian), BLAST, MUSCLE5, Gblocks, RAxML-NG, BEAST2}
           {\textsc{Computing}}{R, Python, shell, Git, Snakemake, reproducible literate programming}

\cvdoubleitem{\textsc{Laboratory}}{DNA extraction and preservation, PCR, microscopy, \textit{Drosophila} tissue dissection, cell culture}
           {\textsc{Field}}{Electrofishing, salmonid sampling and preservation}

\spacesection{}
#+end_export

* Service and Open Source
:PROPERTIES:
:CUSTOM_ID: service-and-open-source
:END:
#+begin_export latex
\cventry{\textsc{June-August 2024}}{\texttt{pydSEAMSlib}: Enhanced Python bindings for d-SEAMS}{Google Summer of Code}{}{Student Developer}{Improved usability and accessibility of pySEAMS through documentation, installation refinements, and user-facing features.}

\cventry{\textsc{June-August 2023}}{\texttt{PYSEAMS}: Python bindings for d-SEAMS}{Google Summer of Code}{}{Student Developer}{Developed Python bindings for d-SEAMS, a molecular dynamics analysis engine for qualitative ice structure classification in confined and bulk systems. Refactored C++ code, removed Lua bindings, improved macOS support, and contributed to documentation, automated testing, and repository maintenance.}

\cventry{\textsc{2022--present}}{IEEE P3173}{IEEE Standards Committee}{}{Secretary}{Supporting the drafting of the IEEE Standard for Endocrine Disrupting Chemical Hazard Labeling.}

\spacesection{}
#+end_export

* Affiliations
:PROPERTIES:
:CUSTOM_ID: affiliations
:END:
#+begin_export latex
\cventry{\textsc{2024--present}}{Nordic Society Oikos}{}{Student Member}{}{}
\cventry{\textsc{2024--present}}{Icelandic Ecological Society (Vistís)}{}{Student Member}{}{}
\cventry{\textsc{2024--present}}{The Icelandic Biological Society (Líffræðigáttin)}{}{Student Member}{}{}
\cventry{\textsc{2022--present}}{British Ecological Society}{}{Student Member}{}{}
\cventry{\textsc{2022--present}}{Genetics Society, UK}{}{Undergraduate Member}{}{}
\cventry{\textsc{2022--present}}{Genetics Society of America}{}{Undergraduate Member}{}{}

\spacesection{}
#+end_export

* Certifications
:PROPERTIES:
:CUSTOM_ID: certifications
:END:
#+begin_export latex
\cventry{\textsc{April 2024}}{Biophotonics}{IIT Kharagpur}{Distinction}{$87\%$}{}
\cventry{\textsc{April 2024}}{Introduction to Professional Scientific communication}{IIT Kanpur}{}{$79\%$}{}
\cventry{\textsc{Sep 2022}}{Applications of machine learning techniques in biology using WEKA}{IIT Madras}{Distinction}{$93\%$}{}
\cventry{\textsc{Nov 2022}}{Practical Python for beginners: a biochemist's guide}{Biochemical Society, U.K.}{}{}{}

%=============================
% this part is a simple cover letter
%\clearpage

%\recipient{Human Resources}{Some Company Ltd.\\Some Street 123\\12345 Some City}
%\date{\today}
%\opening{Dear Sir or Madam,}
%\closing{Sincerely yours,}
%\enclosure[Attached]{curriculum vit\ae{}}

%\makelettertitle

%\lipsum[1-3]

%\makeletterclosing
#+end_export
